AREAS = [
	"langley",
	"langley_city",
	"abbotsford",
	"mision",
	"maple_ridge",
	"pitt_meadows",
	"port_coquitlam",
	"coquitlam_north",
	"coquitlam_south",
	"port_moody",
	"new_westminster",
	"surrey_north",
	"surrey_northwest",
	"surrey_west",
	"surrey_southeast",
	"surrey_south",
	"surrey_northeast",
	"whiterock",
	"delta_central",
	"delta_ladner",
	"tsawwassen",
	"richmond_east",
	"richmond",
	"northvan",
	"northvan_city",
	"westvan",
	"burnaby_sfu",
	"burnaby_north",
	"burnaby_central",
	"burnaby_south",
	"downtown",
	"van_northeast",
	"van_east",
	"van_southeast",
	"van_mountpleasant",
	"van_chinatown",
	"van_south",
	"van_falsecreek",
	"van_kitslano",
	"van_pointgrey",
	"van_ubc",
	"van_kerrisdale"
]

POSTAL_MAP = {
	"V1M": "langley",
	"V2Y": "langley",
	"V2Z": "langley",
	"V4W": "langley",
	"V3A": "langley_city",
	"V2S": "abbotsford",
	"V2T": "abbotsford",
	"V3G": "abbotsford",
	"V4X": "abbotsford",
	"V2V": "mission",
	"V4S": "mission",
	"V2W": "maple_ridge",
	"V2X": "maple_ridge",
	"V4R": "maple_ridge",
	"V3Y": "pitt_meadows",
	"V3B": "port_coquitlam",
	"V3C": "port_coquitlam",
	"V3E": "coquitlam_north",
	"V3J": "coquitlam_south",
	"V3K": "coquitlam_south",
	"V3H": "port_moody",
	"V3L": "new_westminster",
	"V3M": "new_westminster",
	"V3R": "surrey_north",
	"V3T": "surrey_north",
	"V3V": "surrey_northwest",
	"V3W": "surrey_west",
	"V3X": "surrey_west",
	"V3S": "surrey_southeast",
	"V3Z": "surrey_southeast",
	"V4P": "surrey_south",
	"V4A": "surrey_south",
	"V4N": "surrey_northeast",
	"V4B": "whiterock",
	"V4G": "delta_central",
	"V4C": "delta_central",
	"V4E": "delta_central",
	"V4K": "delta_ladner",
	"V4L": "tsawwassen",
	"V4M": "tsawwassen",
	"V6V": "richmond_east",
	"V6W": "richmond_east",
	"V6X": "richmond",
	"V6Y": "richmond",
	"V7A": "richmond",
	"V7C": "richmond",
	"V7E": "richmond",
	"V7G": "northvan",
	"V7H": "northvan",
	"V7J": "northvan",
	"V7K": "northvan",
	"V7N": "northvan",
	"V7R": "northvan",
	"V7L": "northvan_city",
	"V7M": "northvan_city",
	"V7P": "northvan_city",
	"V7S": "westvan",
	"V7T": "westvan",
	"V7V": "westvan",
	"V7W": "westvan",
	"V5A": "burnaby_sfu",
	"V5B": "burnaby_north",
	"V5C": "burnaby_north",
	"V5E": "burnaby_central",
	"V5G": "burnaby_central",
	"V5H": "burnaby_central",
	"V3N": "burnaby_central",
	"V5J": "burnaby_south",
	"V6B": "downtown",
	"V6C": "downtown",
	"V6E": "downtown",
	"V6G": "downtown",
	"V6Z": "downtown",
	"V7X": "downtown",
	"V7Y": "downtown",
	"V5K": "van_northeast",
	"V5L": "van_northeast",
	"V5M": "van_east",
	"V5N": "van_east",
	"V5R": "van_east",
	"V5P": "van_southeast",
	"V5S": "van_southeast",
	"V5T": "van_mountpleasant",
	"V5Y": "van_mountpleasant",
	"V5V": "van_mountpleasant",
	"V6A": "van_chinatown",
	"V5W": "van_south",
	"V5X": "van_south",
	"V5Z": "van_falsecreek",
	"V6H": "van_falsecreek",
	"V6J": "van_kitslano",
	"V6K": "van_kitslano",
	"V6L": "van_kitslano",
	"V6R": "van_pointgrey",
	"V6S": "van_pointgrey",
	"V6T": "van_ubc",
	"V6N": "van_kerrisdale",
	"V6M": "van_kerrisdale",
	"V6P": "van_kerrisdale"
}